### PR TITLE
"feat: added ucan auth using w3up-client"

### LINKED ISSUE #1: Implement UCAN auth for web3.storage and nft.storage
Right now UCANs don't work properly (I commented them out). It would be nice to write a nice and simple function for uploading CARs on web3.storage with utilization of UCANs.

Please submit a function called `uploadCAR` to the `utils/ipfs.ts` file

### ucan.storage integration

Example of an error:

```ts
export const uploadCar = async (car: Blob, ucanToken: string, did: string) => {
  const res = await fetch('https://api.nft.storage/upload', {
    method: 'POST',
    headers: { 'Content-Type': 'application/car', 'Authorization': `Bearer ${ucanToken}`, 'x-agent-did': did  },
    body: car
  })
  const text = await res.text()
  console.log(res.status, text)
}
```

I get this kind of error:

```sh
500 {"ok":false,"error":{"code":"TypeError","message":"Cannot read properties of null (reading 'split')"}}
```

### general w3up UCAN

```ts
import { create } from '@web3-storage/w3up-client'

export const uploadToWeb3Storage = async (car: Blob, configEmail?: Email) => {
  const client = await create()
  if (!configEmail) {
    const email = 'hello@example.com'
    console.log(`An email to ${email} was sent`)
    try { await client.authorize(email) } catch { return console.error(kleur.red(`Failed to send ${email}`)) }
  } else {
    try {
      await client.registerSpace(configEmail, { provider: 'did:web:web3.storage' })
    } catch (e) {
      const space = await client.createSpace()
      await client.setCurrentSpace(space.did())
    }
  }
  console.log(await client.uploadCAR(car))
}
```

```sh
file:///home/v1rtl/Coding/flash-cli/node_modules/.pnpm/@web3-storage+upload-client@9.0.1/node_modules/@web3-storage/upload-client/src/store.js:78
    throw new Error(`failed ${StoreCapabilities.add.can} invocation`, {
          ^
Error: failed store/add invocation
    at add (file:///home/v1rtl/Coding/flash-cli/node_modules/.pnpm/@web3-storage+upload-client@9.0.1/node_modules/@web3-storage/upload-client/src/store.js:78:11) {
  [cause]: {
    name: 'Error',
    stack: 'Error: Space has no storage provider\n' +
      '    at Object.allocateSpace (/upload-api/access.js:40:22)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async Promise.all (index 0)\n' +
      '    at <anonymous> (/node_modules/@web3-storage/upload-api/src/store/add.js:19:58)\n' +
      '    at invoke2 (/node_modules/@ucanto/server/src/server.js:139:22)\n' +
    message: 'Space has no storage provider'
  }
}
```

I'd prefer if we'd use w3up for both nft.storage and web3.storage cuz ucan.storage is going to get deprecated.

### PR DESCRIPTION
**Pull request by Clish254**
Fixes #1 
I used [w3up-client](https://github.com/web3-storage/w3up/tree/57182b1d193924a6c5eefa3e01ef56719303c42e/packages/w3up-client) for the ucan auth flow and file upload.

### CODE REVIEW

File: flash.ts [hunk 1]
```diff
@@ -46,6 +48,22 @@ const prompt = async () =>
         },
       ],
     },
+    {
+      name: 'email',
+      type: 'text',
+      message: 'What is your email address?',
+      validate: value => (!emailPattern.test(value) ? 'Invalid email' : true),
```
Comment (talentlessguy) [inline flash.ts:55]: oh good idea to validate email!

File: flash.ts [hunk 2]
```diff
@@ -46,6 +48,22 @@ const prompt = async () =>
         },
       ],
     },
+    {
+      name: 'email',
+      type: 'text',
+      message: 'What is your email address?',
```
Comment (talentlessguy) [inline flash.ts:54]: I think it's better to ask smth like this in the message: `Verify your email to confirm that you're not a bot`
